package com.example.android.textbookexchange2;

/**
 * Created by cyoo0706 on 10/30/16.
 */

public class Product {
    private float mPrice;
    private String mName;
    private final int mProductID;
    private final int mUserID;

    /** Image resource ID for the word */
    private int mPictureID = NO_IMAGE_PROVIDED;

    /** Constant value that represents no image was provided for this word */
    private static final int NO_IMAGE_PROVIDED = -1;

    /**
     * Constructor (no picture)
     *
     * @param price User determined price for item
     * @param name User determined product name
     * @param userID Associate product with user who created product description
     * @param productID Unique to each product, autogenerated ID number
     */
    public Product(float price, String name, int userID, int productID) {
        this.mPrice = price;
        this.mName = name;
        this.mUserID = userID;
        this.mProductID = productID;
    }

    /**
     * Constructor (with picture)
     *
     * @param price User determined price for item
     * @param name User determined product name
     * @param userID Associate product with user who created product description
     * @param productID Unique to each product, autogenerated ID number
     * @param pictureID Resource ID for thumbnail image in browse screen
     */
    public Product(float price, String name, int userID, int productID, int pictureID) {
        this.mPrice = price;
        this.mName = name;
        this.mUserID = userID;
        this.mProductID = productID;
        this.mPictureID = pictureID;
    }

    //Getters
    public float getPrice() {
        return mPrice;
    }

    public String getName() {
        return mName;
    }

    public int getProductID() {
        return mProductID;
    }

    public int getUserID() {
        return mUserID;
    }

    public int getPictureID() {
        return mPictureID;
    }

    //Setters
    public void setPrice(float price) {
        this.mPrice = price;
    }

    public void setName(String Name) {
        this.mName = Name;
    }

    //Checks for image
    public boolean hasImage() {
        return mPictureID != NO_IMAGE_PROVIDED;
    }

}
